on:
  release:
    types: [published]

jobs:
  package-publish:
    name: Publish package to wally registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup foreman
        uses: rojo-rbx/setup-foreman@6d3c8043db88319f8482262680b37f73595a8686
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish wally package
        run: /
          echo ${{ secrets.WALLY_AUTH }} > ~/.wally/auth.toml
          wally publish