name: Lua linting
on:
  push:
    branches:
    - 'v*.*.*'
    - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - 'v*.*.*'
      - master
    paths:
      - 'src/**'
jobs:
  selene-lint:
    name: Lint src/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      
      - name: Setup foreman
        uses: rojo-rbx/setup-foreman@62bc697705339a6049f74c9d0ff6d39cffc993e5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name : Run selene
        run: |
          selene src/